### ISSUE TITLE
Spawning inside stone on new world

### ISSUE THREAD

**Issue by Teraphina** [GreatOrator/FallCraft#34]
ok so i make a new world and spawn in stone (just wanted to post the first part of the issue here)

ok i think i know whats happening, i am "falling" while the world is loading and instead of the game popping me up onto the actual spawn it is putting me at the y level i am at when the world finishes loading

and to make sure this is covered i am not moving while the world is loading.

**Comment by eDilettante** [comment]
Similar results here with new worlds in 063, five times spawned inside stone/gravel (levels Y 55-63), three times underwater (no land visible on swimming to surface), and once at level 63 on top of some snow, but got the glitchy shaking where you have to break the block under you before you can move. Half of the attempts were using BoP generation, the other half just default vanilla generation.
I know it won't be like this when there's a pre-generated world, but this wasn't happening on new spawns in previous versions.

**Comment by GreatOrator** [comment]
Unfortunately that is because in the latest update the mod perfect spawn has been added since we actually have a default map being worked on (not included as it is not ready for public consumption) the mod testing phase for the most part has fortunately been completed and the start coordinates on the default map are within a mountain meaning if you create a new standard map, you will spawn in ground.
