### ISSUE TITLE
No NPC's

### ISSUE THREAD

**Issue by NeekotheFoxx** [GreatOrator/FallCraft#43]
When loading the game, i installed the map and when loaded, the only NPC available is the shopkeeper lake, who doesnt have a skin and is just black and purple blocks. The quest journal, only popping up when i press the ~ key, says i need to speak to people but there are no other people available to speak with an all she says to me is something along the lines of hello i hope you have a good day.

**Comment by GreatOrator** [comment]
That is correct, the map is in beta status right now, mostly for anyone willing to go through the trouble to download to make sure the map is good and no weirdness.  The quest book is also being worked on and has not been uploaded yet.

It's coming, I promise, but not yet in a playable status which is why the splash screen says:

Please remember, the map available through this tool to download is not the actual map that will be released.  It is simply here as a placeholder during testing.  If you truly want the map, you can download it from github, but I will not troubleshoot map issues if you have any.

Thank you for your interest though and by all means, if you find any bugs related to the mods or the map related to the actual builds, let me know.
